stages:
  setup:
    cmd:  ipynb-py-convert git_quake.ipynb git_quake.py
    deps:
    - git_quake.ipynb
    outs:
    - git_quake.py  
  train:
    cmd: python git_quake.py
    deps:
    - git_quake.py
    outs:
    - estimators.png
    - learning_rate.png
    - reg_alpha.png
    - max_depth.png
    - reg_lambda.png
    - submission.csv
