name: compare-and-update-metrics
on:
  push:
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://iterativeai/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global --add safe.directory /__w/driven-quake/driven-quake
            python -m pip install -r require.txt
            dvc repro
            git fetch --prune
            
            
            echo "## confusion matrix" >> report.md
            cml publish score.json --md >>report.md
            cml publish estimators.png --md >> report.md
            cml send-comment report.md
            
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: score.json
          commit-msg: Update score.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
